#!/usr/bin/env bash
wget https://boostorg.jfrog.io/artifactory/main/release/1.76.0/source/boost_1_76_0.tar.bz2
tar --bzip2 -xf boost_1_76_0.tar.bz2 
cd boost_1_76_0
./bootstrap.sh --help
./bootstrap.sh --prefix=/data/data/com.termux/files/usr 
./b2 install
